services:
  base:
    container_name: base-nodejs
    build: .
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://db_user_lsv:db_pass_lsv@201.219.216.217:3324/db_lsv
    ports:
      - '4393:4393'
    volumes:
      - .:/base
      - /base/node_modules
      - ./env_file:/base/.env
    command: >
      sh -c "npx prisma migrate deploy && npx prima generate"