services:
  base:
    container_name: base-nodejs
    build: .
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root_pass_lsv@201.219.216.217:3324/db_lsv
      - MAIL_HOST="server1.lsv-tech.com"
      - MAIL_PORT="465"
      - EMAIL_ADMIN="qa@lsv-tech.com"
      - PASS_EMAIL_ADMIN="o].tGf)%=$GK"
      - PASS_ADMIN="Testing24@"
      - PORT="3495"
      - KEY_SECRET="qwerty"
      - REFRESH_KEY="qazwer"
    ports:
      - '3495:3495'
    volumes:
      - .:/base
    command: >
      sh -c "npx prisma migrate deploy && npx prisma generate && npm run start"
